"""Update Book model column names

Revision ID: 250cd5f71c1f
Revises: 48c33c522789
Create Date: 2026-06-16 07:40:13.205032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '250cd5f71c1f'
down_revision: Union[str, Sequence[str], None] = '48c33c522789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('ISBN', sa.Integer(), nullable=False))
    op.add_column('books', sa.Column('book_name', sa.String(), nullable=False))
    op.add_column('books', sa.Column('book_author', sa.String(), nullable=False))
  
    op.drop_index(op.f('ix_books_id'), table_name='books')
    op.create_index(op.f('ix_books_ISBN'), 'books', ['ISBN'], unique=False)
    op.create_unique_constraint('uq_book_name', 'books', ['book_name'])
    op.create_unique_constraint(None, 'books', ['book_name'])
    op.drop_column('books', 'author')
    op.drop_column('books', 'title')
    op.drop_column('books', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('books', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('books', sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'books', type_='unique')
    op.drop_constraint('uq_book_name', 'books', type_='unique')
    op.drop_index(op.f('ix_books_ISBN'), table_name='books')
    op.create_index(op.f('ix_books_id'), 'books', ['id'], unique=False)
   
    op.drop_column('books', 'book_author')
    op.drop_column('books', 'book_name')
    op.drop_column('books', 'ISBN')
    # ### end Alembic commands ###
